{% set version = "0.2.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modeldb
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/modeldb_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/modeldb/modeldb_{{ version }}.tar.gz
  sha256: 6f3c05d0520743851f29a9f88f10093639bb12902763224984f11c6a886635b7

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr >=0.7
    - r-ggplot2
    - r-progress
    - r-purrr
    - r-rlang
    - r-tibble
    - r-tidypredict
  run:
    - r-base
    - r-dplyr >=0.7
    - r-ggplot2
    - r-progress
    - r-purrr
    - r-rlang
    - r-tibble
    - r-tidypredict

test:
  commands:
    - $R -e "library('modeldb')"           # [not win]
    - "\"%R%\" -e \"library('modeldb')\""  # [win]

about:
  home: https://github.com/tidymodels/modeldb
  license: MIT
  summary: Uses 'dplyr' and 'tidyeval' to fit statistical models inside the database. It currently supports KMeans and linear regression models.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: modeldb
# Version: 0.1.2
# Title: Fits Models Inside the Database
# Description: Uses 'dplyr' and 'tidyeval' to fit statistical models inside the database. It currently supports KMeans and linear regression models.
# Authors@R:  person("Edgar", "Ruiz", email = "edgar@rstudio.com", role = c("aut", "cre"))
# Depends: R (>= 3.1)
# Imports: dplyr(>= 0.7), rlang, purrr, tibble, progress, ggplot2
# Suggests: dbplyr, testthat, knitr, rmarkdown, nycflights13, RSQLite, methods, DBI, covr
# License: GPL-3
# URL: https://github.com/edgararuiz/modeldb
# BugReports: https://github.com/edgararuiz/modeldb/issues
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-03-02 21:11:18 UTC; edgar
# Author: Edgar Ruiz [aut, cre]
# Maintainer: Edgar Ruiz <edgar@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-03-02 21:30:03 UTC
