travis:
  secure:
    BINSTAR_TOKEN: WhUyoWhjpPQRSFQwQhjrNqrkqCUoKZ52AEe+t251oyqR7I8mon51cq4pjj8PBEazMDvvjbIVHx7a/fbXQKG+CKWf/QkRTNK5iJ6hCqY2zRB2FKWzVhFo6jf/nOT5ULe2xgPbZ0mmKZYX2Z0pL9X5bqt9OTfZ9h4Ybs6BjvxuaANaWgyhw/jbiJCe5vpCDJycWv4jERh9NB2h8y/K07eNAbFXWYbogEr6MMCTaIbyROC06TNVzBIewuQrZGyj4XaAd7Dh9xD/ixDLlgAt7E8QHe/aJz9bK+AVLsswbmJBj4t/5ojkwS9aLztI8ZJjIl5PA7SNBhG7pM5FckQ5QvXjWJyFAEttXrkZWXZo/UL9yGr0GNfh8aZYdribCSq/Aq9pj+G78klGthZoAo6nIxmq68dny1VzNeaFsk2mbCOlOtjyCO+3NYE9ngRbpHa0e/6J9KRcmkRH8VW8C1Q790gTlQh3nKrxCHv6e/DUZdLeqGxKQ1ZCmaX7qTIC1H8kUaVxr8wnu5mX01HaorItG4LIfXmdZ7S7/jDLQavk9Uqyxgo9Ef9K/fikUvY0HAsQz7A1NxlaadKp2psPfCHT1WmM24vSCqRfP05LZnL3M5z9N6N4jpbw9ZO6VRHGGIXa5GcPvBazvhPU5bKeGTHDD7o6Kg03mfgk2bRlwdIuPPSl0bY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
